export const LOAD_FEED_START = 'LOAD_FEED_START';
export const LOAD_FEED_SUCCESS = 'LOAD_FEED_SUCCESS';
export const LOAD_FEED_ERROR = 'LOAD_FEED_ERROR';
export const CHANGE_SEARCH_TERM = 'CHANGE_SEARCH_TERM';
